"""
Train & compare 8 car-price regression models (AutoIntel — ML comparison pipeline).

This module reproduces the logic that previously lived in
``notebooks/car_price_ml_comparison.ipynb`` (which is now a slimmed demo artifact).

Run it from the repository root:

    python scripts/train_car_price_comparison.py

Reads preprocessed artifacts generated by ``scripts/backfills/prepare_ml_data.py``:

    ml_ready/X_train.npy      (8919, 39) — log1p-target, scaled
    ml_ready/X_test.npy       (2230, 39)
    ml_ready/y_train.npy      (8919,)    — log1p(Price)
    ml_ready/y_test.npy       (2230,)
    ml_ready/feature_names.npy

Writes report artifacts under ``report_output/images``:

    model_comparison_r2.png
    model_rmse_mae.png
    radar_comparison.png
    feature_importance.png
    residual_analysis.png

The 8 models are trained on the log-transformed target; all metrics are reported
in the original INR scale via ``np.expm1``.
"""

from __future__ import annotations

import os
import time
import warnings
from pathlib import Path
from typing import Any, Protocol, TypeVar

import matplotlib
import numpy as np
import pandas as pd
import xgboost as xgb
from matplotlib import pyplot as plt
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import Lasso, LinearRegression, Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

warnings.filterwarnings("ignore")

matplotlib.use("Agg")

BASE_DIR = Path(__file__).resolve().parent.parent
ML_READY = BASE_DIR / "ml_ready"
REPORT_DIR = BASE_DIR / "report_output"
IMG_DIR = REPORT_DIR / "images"

FIG_SIZE = (14, 6)
COLORS = plt.colormaps["viridis"]
MODEL_COLORS = plt.colormaps["tab10"]


class _Fitted(Protocol):
    """Protocol for fitted sklearn regressors used by the shared models dict."""

    fit: Any
    predict: Any


Model = TypeVar("Model", bound=_Fitted)


def load_ml_ready() -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, list[str]]:
    """Load preprocessed training/test arrays and feature names."""
    X_train = np.load(ML_READY / "X_train.npy")
    X_test = np.load(ML_READY / "X_test.npy")
    y_train = np.load(ML_READY / "y_train.npy")
    y_test = np.load(ML_READY / "y_test.npy")
    feature_names = list(np.load(ML_READY / "feature_names.npy", allow_pickle=True))
    return X_train, X_test, y_train, y_test, feature_names


def build_models() -> dict[str, Model]:
    """Return the 8 regression models with tuned configs."""
    return {
        "Linear Regression": LinearRegression(),
        "Ridge": Ridge(alpha=1.0),
        "Lasso": Lasso(alpha=0.001, max_iter=10000),
        "Random Forest": RandomForestRegressor(
            n_estimators=300,
            max_depth=15,
            min_samples_leaf=2,
            min_samples_split=5,
            n_jobs=-1,
            random_state=42,
        ),
        "Gradient Boosting": GradientBoostingRegressor(
            n_estimators=200,
            max_depth=5,
            learning_rate=0.05,
            min_samples_leaf=2,
            subsample=0.8,
            random_state=42,
        ),
        "XGBoost": xgb.XGBRegressor(
            n_estimators=300,
            max_depth=3,
            learning_rate=0.1,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=42,
            verbosity=0,
        ),
        "SVR": SVR(kernel="rbf", C=100, gamma="scale"),
        "KNN": KNeighborsRegressor(n_neighbors=7, weights="distance"),
    }


def train_and_evaluate(
    X_train: np.ndarray, X_test: np.ndarray, y_train: np.ndarray, y_test: np.ndarray
) -> tuple[pd.DataFrame, dict[str, Model]]:
    """Fit every model once and return a metrics table plus the fitted models.

    The fitted ``models`` dict is returned so that downstream visuals and
    residual analysis reuse the exact estimators that produced the metrics
    (no second ``build_models()`` call, no unfitted estimators).
    """
    models: dict[str, Model] = build_models()
    header = f"{'Model':<22} {'Train R²':<10} {'Test R²':<10} {'RMSE':<14} {'MAE':<14} {'Time (s)':<8}"
    print(header)
    print("=" * len(header))

    results: list[dict[str, object]] = []
    for name, model in models.items():
        start = time.time()
        model.fit(X_train, y_train)
        elapsed = time.time() - start

        y_train_pred_log = model.predict(X_train)
        y_test_pred_log = model.predict(X_test)
        y_train_pred = np.expm1(y_train_pred_log)
        y_test_pred = np.expm1(y_test_pred_log)

        y_train_orig = np.expm1(y_train)
        y_test_orig = np.expm1(y_test)

        train_r2 = r2_score(y_train_orig, y_train_pred)
        test_r2 = r2_score(y_test_orig, y_test_pred)
        rmse = float(np.sqrt(mean_squared_error(y_test_orig, y_test_pred)))
        mae = float(mean_absolute_error(y_test_orig, y_test_pred))
        cv_scores = cross_val_score(model, X_train, y_train, cv=3, scoring="r2")
        cv_mean = float(cv_scores.mean())
        cv_std = float(cv_scores.std())

        results.append(
            {
                "Model": name,
                "Train R²": train_r2,
                "Test R²": test_r2,
                "RMSE": rmse,
                "MAE": mae,
                "CV R² Mean": cv_mean,
                "CV R² Std": cv_std,
                "Time (s)": round(elapsed, 2),
            }
        )
        print(
            f"{name:<22} {train_r2:<10.4f} {test_r2:<10.4f} "
            f"Rs.{rmse:<10,.0f} Rs.{mae:<10,.0f} {elapsed:<8.2f}"
        )

    print("\nTraining complete!")
    return pd.DataFrame(results), models


def save_summary_table(results_df: pd.DataFrame, out_dir: Path | None = None) -> None:
    """Print and persist the formatted results summary."""
    out_dir = out_dir or REPORT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    display_cols = [
        "Model", "Train R²", "Test R²", "RMSE", "MAE", "CV R² Mean", "CV R² Std", "Time (s)",
    ]
    display_df = results_df[display_cols].copy()
    display_df.index = display_df.index + 1  # 1-based index is display-only

    display_df["Train R²"] = display_df["Train R²"].map(lambda x: f"{x:.4f}")
    display_df["Test R²"] = display_df["Test R²"].map(lambda x: f"{x:.4f}")
    display_df["CV R² Mean"] = display_df["CV R² Mean"].map(lambda x: f"{x:.4f}")
    display_df["CV R² Std"] = display_df["CV R² Std"].map(lambda x: f"{x:.4f}")
    display_df["RMSE"] = display_df["RMSE"].map(lambda x: f"Rs.{x:,.0f}")
    display_df["MAE"] = display_df["MAE"].map(lambda x: f"Rs.{x:,.0f}")

    print("\n=== Model Performance Comparison (original INR scale) ===")
    print()
    print(display_df.to_string(index=True))

    best_test_r2 = results_df.loc[results_df["Test R²"].idxmax()]
    best_rmse = results_df.loc[results_df["RMSE"].idxmin()]
    best_mae = results_df.loc[results_df["MAE"].idxmin()]

    print(f"\n{'=' * 60}")
    print(f"Best Test R²:  {best_test_r2['Model']} ({best_test_r2['Test R²']:.4f})")
    print(f"Lowest RMSE:   {best_rmse['Model']} (Rs.{best_rmse['RMSE']:,.0f})")
    print(f"Lowest MAE:    {best_mae['Model']} (Rs.{best_mae['MAE']:,.0f})")

    with open(out_dir / "model_comparison_summary.txt", "w", encoding="utf-8") as fh:
        fh.write(display_df.to_string(index=True))
        fh.write("\n")


def bar_chart_test_r2(results_df: pd.DataFrame, out_path: Path) -> None:
    """Per-model Test R² bar chart."""
    sorted_df = results_df.sort_values("Test R²")
    fig, ax = plt.subplots(figsize=FIG_SIZE)
    colors = COLORS(np.linspace(0.2, 0.9, len(sorted_df)))
    bars = ax.barh(
        range(len(sorted_df)),
        sorted_df["Test R²"].values,
        color=colors,
        edgecolor="white",
    )
    ax.set_yticks(range(len(sorted_df)))
    ax.set_yticklabels(sorted_df["Model"].values)
    ax.set_xlabel("Test R² Score")
    ax.set_title("Model Performance Comparison - R² Score (higher is better)", fontsize=14, fontweight="bold")
    ax.set_xlim(0, 1.0)

    for i, (_bar, val) in enumerate(zip(bars, sorted_df["Test R²"].values, strict=False)):
        ax.text(val + 0.01, i, f"{val:.4f}", va="center", fontsize=10, fontweight="bold")

    fig.tight_layout()
    fig.savefig(out_path, dpi=120, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {out_path}")


def rmse_mae_chart(results_df: pd.DataFrame, out_path: Path) -> None:
    """Side-by-side RMSE & MAE bar charts (values scaled to lakhs)."""
    sorted_idx = results_df["RMSE"].argsort()
    fig, axes = plt.subplots(1, 2, figsize=FIG_SIZE)

    ax = axes[0]
    colors_rmse = plt.colormaps["RdYlGn_r"](np.linspace(0.2, 0.9, len(results_df)))
    ax.barh(
        range(len(results_df)),
        results_df["RMSE"].values[sorted_idx] / 1e5,
        color=colors_rmse,
        edgecolor="white",
    )
    ax.set_yticks(range(len(results_df)))
    ax.set_yticklabels(results_df["Model"].values[sorted_idx])
    ax.set_xlabel("RMSE (in lakhs)")
    ax.set_title("Root Mean Squared Error (lower is better)", fontweight="bold")

    ax = axes[1]
    ax.barh(
        range(len(results_df)),
        results_df["MAE"].values[sorted_idx] / 1e5,
        color=colors_rmse,
        edgecolor="white",
    )
    ax.set_yticks(range(len(results_df)))
    ax.set_yticklabels(results_df["Model"].values[sorted_idx])
    ax.set_xlabel("MAE (in lakhs)")
    ax.set_title("Mean Absolute Error (lower is better)", fontweight="bold")

    fig.tight_layout()
    fig.savefig(out_path, dpi=120, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {out_path}")


def radar_chart(results_df: pd.DataFrame, out_path: Path) -> None:
    """Radars: 5 normalized metrics (RMSE/MAE/Time inverted, higher = better)."""
    radar_metrics = ["Test R²", "RMSE", "MAE", "CV R² Mean", "Time (s)"]
    radar_labels = ["Test R²", "RMSE (inv)", "MAE (inv)", "CV R² Mean", "Speed (inv)"]

    radar_data = results_df[radar_metrics].copy()

    for col in ["RMSE", "MAE"]:
        min_val = radar_data[col].min()
        max_val = radar_data[col].max()
        if max_val > min_val:
            radar_data[col] = 1 - (radar_data[col] - min_val) / (max_val - min_val)
        else:
            radar_data[col] = 1.0

    time_min = radar_data["Time (s)"].min()
    time_max = radar_data["Time (s)"].max()
    if time_max > time_min:
        radar_data["Time (s)"] = 1 - (radar_data["Time (s)"] - time_min) / (time_max - time_min)
    else:
        radar_data["Time (s)"] = 1.0

    test_r2_min = radar_data["Test R²"].min()
    test_r2_max = radar_data["Test R²"].max()
    if test_r2_max > test_r2_min:
        radar_data["Test R²"] = (radar_data["Test R²"] - test_r2_min) / (test_r2_max - test_r2_min)
    else:
        radar_data["Test R²"] = 1.0

    cv_min = radar_data["CV R² Mean"].min()
    cv_max = radar_data["CV R² Mean"].max()
    if cv_max > cv_min:
        radar_data["CV R² Mean"] = (radar_data["CV R² Mean"] - cv_min) / (cv_max - cv_min)
    else:
        radar_data["CV R² Mean"] = 1.0

    n = len(radar_metrics)
    angles = [i / float(n) * 2 * np.pi for i in range(n)]
    angles += angles[:1]

    model_colors = MODEL_COLORS(np.linspace(0, 1, len(results_df)))
    fig, ax = plt.subplots(figsize=(12, 10), subplot_kw={"polar": True})

    for idx, (_, row) in enumerate(results_df.iterrows()):
        values = radar_data.loc[idx, radar_metrics].values.tolist()
        values += values[:1]
        ax.plot(angles, values, "o-", linewidth=2, label=row["Model"], color=model_colors[idx])
        ax.fill(angles, values, alpha=0.05, color=model_colors[idx])

    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(radar_labels, fontsize=11, fontweight="bold")
    ax.set_ylim(0, 1.05)
    ax.set_yticks([0.2, 0.4, 0.6, 0.8, 1.0])
    ax.set_yticklabels(["0.2", "0.4", "0.6", "0.8", "1.0"], fontsize=8, color="gray")
    ax.set_title("ML Algorithm Comparison - Radar Chart", fontsize=16, fontweight="bold", pad=25)
    ax.legend(loc="upper right", bbox_to_anchor=(1.35, 1.1), fontsize=9, framealpha=0.9)
    ax.text(
        0, -0.15,
        "Higher values are better across all dimensions. "
        "RMSE, MAE & Time are inverted so that outward = better performance.",
        transform=ax.transAxes, ha="center", fontsize=9, color="gray",
    )
    fig.tight_layout()
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {out_path}")


def feature_importance(models: dict[str, object], feature_names: list[str], out_path: Path) -> None:
    """XGBoost top-15 feature importance chart."""
    xgb_model = models["XGBoost"]
    if not hasattr(xgb_model, "feature_importances_"):
        print(f"SKIP feature importance — {type(xgb_model).__name__} has no feature_importances_")
        return
    importance = xgb_model.feature_importances_
    sorted_idx = np.argsort(importance)[::-1]
    top_n = 15

    fig, ax = plt.subplots(figsize=(10, 6))
    top_features = [feature_names[i] for i in sorted_idx[:top_n]]
    top_values = importance[sorted_idx[:top_n]]
    colors = plt.colormaps["Blues"](np.linspace(0.3, 0.9, top_n))
    ax.barh(range(top_n), top_values[::-1], color=colors[::-1], edgecolor="white")
    ax.set_yticks(range(top_n))
    ax.set_yticklabels(top_features[::-1])
    ax.set_xlabel("Feature Importance")
    ax.set_title("Top 15 Feature Importances (XGBoost)", fontsize=14, fontweight="bold")
    fig.tight_layout()
    fig.savefig(out_path, dpi=120, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {out_path}")


def residual_analysis(models: dict[str, object], X_test: np.ndarray, y_test: np.ndarray, out_path: Path, best_model: object | None = None) -> None:
    """Actual vs predicted / residuals / predicted vs residual panels."""
    fitted: object | None = best_model if best_model is not None else next(
        (m for m in models.values() if hasattr(m, "predict")), None
    )
    if fitted is None:
        raise RuntimeError("best model not found; pass best_model or call train_and_evaluate first")
    if not hasattr(fitted, "predict"):
        raise TypeError(f"best_model must expose predict(); got {type(fitted).__name__}")

    y_pred = fitted.predict(X_test)
    residuals = y_test - y_pred

    fig, axes = plt.subplots(1, 3, figsize=(16, 5))

    axes[0].scatter(y_pred / 1e5, residuals / 1e5, alpha=0.4, s=10, color="steelblue")
    axes[0].axhline(y=0, color="red", linestyle="--", linewidth=1)
    axes[0].set_xlabel("Predicted Price (in lakhs)")
    axes[0].set_ylabel("Residuals (in lakhs)")
    axes[0].set_title(f"Residuals vs Predicted\n{best_model.__class__.__name__}", fontweight="bold")

    axes[1].hist(residuals / 1e5, bins=40, color="coral", edgecolor="white", alpha=0.8)
    axes[1].axvline(x=0, color="red", linestyle="--", linewidth=1)
    axes[1].set_xlabel("Residuals (in lakhs)")
    axes[1].set_ylabel("Frequency")
    axes[1].set_title("Distribution of Residuals", fontweight="bold")

    axes[2].scatter(y_test / 1e5, y_pred / 1e5, alpha=0.4, s=10, color="seagreen")
    min_val = min(y_test.min(), y_pred.min()) / 1e5
    max_val = max(y_test.max(), y_pred.max()) / 1e5
    axes[2].plot([min_val, max_val], [min_val, max_val], "r--", linewidth=1, label="Perfect Prediction")
    axes[2].set_xlabel("Actual Price (in lakhs)")
    axes[2].set_ylabel("Predicted Price (in lakhs)")
    axes[2].set_title("Actual vs Predicted", fontweight="bold")
    axes[2].legend()

    fig.tight_layout()
    fig.savefig(out_path, dpi=120, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {out_path}")


def tune_top_tree_models(X_train: np.ndarray, y_train: np.ndarray, X_test: np.ndarray, y_test: np.ndarray) -> dict[str, object]:
    """GridSearchCV the top 3 tree-based models (GB, XGBoost, RF)."""
    tune_config = {
        "Gradient Boosting": {
            "model": GradientBoostingRegressor(random_state=42),
            "grid": {
                "n_estimators": [100, 200, 300],
                "max_depth": [3, 5, 7],
                "learning_rate": [0.05, 0.1],
                "min_samples_leaf": [2, 5],
                "subsample": [0.8, 1.0],
            },
        },
        "XGBoost": {
            "model": xgb.XGBRegressor(random_state=42, verbosity=0),
            "grid": {
                "n_estimators": [100, 200, 300],
                "max_depth": [3, 6, 9],
                "learning_rate": [0.05, 0.1, 0.2],
                "subsample": [0.8, 1.0],
                "colsample_bytree": [0.8, 1.0],
            },
        },
        "Random Forest": {
            "model": RandomForestRegressor(random_state=42, n_jobs=-1),
            "grid": {
                "n_estimators": [100, 200, 300],
                "max_depth": [10, 15, None],
                "min_samples_leaf": [2, 5],
                "min_samples_split": [2, 5],
            },
        },
    }

    print("=" * 70)
    print(f"{'Model':<22} {'Best CV R² (log)':<18} {'Best Params'}")
    print(f"{'=' * 70}")

    tuned_models: dict[str, object] = {}
    for name, config in tune_config.items():
        gs = GridSearchCV(config["model"], config["grid"], cv=3, scoring="r2", n_jobs=-1, verbose=0)
        gs.fit(X_train, y_train)
        tuned_models[name] = gs.best_estimator_

        print(
            f"{name:<22} {gs.best_score_:<18.4f}",
            end="",
        )
        params_str = ", ".join(f"{k}={v}" for k, v in gs.best_params_.items())
        print(params_str)

        y_pred = np.expm1(gs.best_estimator_.predict(X_test))
        y_test_orig = np.expm1(y_test)
        r2 = r2_score(y_test_orig, y_pred)
        rmse = float(np.sqrt(mean_squared_error(y_test_orig, y_pred)))
        print(f"{'':22} Test R2 (orig): {r2:.4f}, RMSE: Rs.{rmse:,.0f}")

    print(f"\n{'=' * 70}")
    print("Tuning complete! See results below.")
    return tuned_models


def main() -> None:
    X_train, X_test, y_train, y_test, feature_names = load_ml_ready()
    print(f"X_train shape: {X_train.shape}")
    print(f"X_test shape:  {X_test.shape}")
    print(f"y_train shape: {y_train.shape}  (log1p-transformed)")
    print(f"y_test shape:  {y_test.shape}  (log1p-transformed)")
    print(f"Number of features: {len(feature_names)}")
    print(f"First 10 feature names: {feature_names[:10]}")
    print(f"y_train range: {y_train.min():.4f} - {y_train.max():.4f}")
    print(f"Equivalent INR: Rs.{np.expm1(y_train.min()):,.0f} - Rs.{np.expm1(y_train.max()):,.0f}")

    IMG_DIR.mkdir(parents=True, exist_ok=True)
    fitted_models: dict[str, object]
    results_df, fitted_models = train_and_evaluate(X_train, X_test, y_train, y_test)
    save_summary_table(results_df)

    bar_chart_test_r2(results_df, IMG_DIR / "model_comparison_r2.png")
    rmse_mae_chart(results_df, IMG_DIR / "model_rmse_mae.png")
    radar_chart(results_df, IMG_DIR / "radar_comparison.png")
    feature_importance(fitted_models, feature_names, IMG_DIR / "feature_importance.png")
    best_model = fitted_models.get(results_df.loc[results_df["Test R²"].idxmax(), "Model"])
    if best_model is not None:
        residual_analysis(fitted_models, X_test, y_test, IMG_DIR / "residual_analysis.png", best_model=best_model)

    if os.environ.get("RUN_TUNING", "0") == "1":
        tune_top_tree_models(X_train, y_train, X_test, y_test)


if __name__ == "__main__":
    main()
